nl-design-system/candidate

packages/components-css/paragraph-css/package.json, packages/components-react/paragraph-react/package.json
Scoped packages are private by default and need a `publishConfig` with `"access": "public"` to be published to the npm registry.
=> chore: add publishConfig

.github/dependabot.yml, package.json, pnpm-lock.yaml
Pin the @types/node version to the version that is used in `.nvmrc` and in `package.json#engines.node`
Add a comment so as to not forget to update `@types/node` manually
=> build: pin @types/node

packages/components-css/paragraph-css/src/html/_mixins.scss, packages/components-css/paragraph-css/src/html/paragraph.scss, packages/components-css/paragraph-css/src/paragraph.scss
See https://sass-lang.com/blog/import-is-deprecated/ for more information
=> chore: replace Sass @imports

packages/components-react/heading-1-react/rollup.config.mjs, packages/components-react/heading-2-react/rollup.config.mjs, packages/components-react/heading-3-react/rollup.config.mjs, packages/components-react/heading-4-react/rollup.config.mjs, packages/components-react/heading-5-react/rollup.config.mjs, packages/components-react/heading-6-react/rollup.config.mjs, packages/components-react/paragraph-react/rollup.config.mjs, packages/components-react/rollupConfig.mjs
Reduce duplication of the rollup configuration by importing from a higher-level directory instead of repeating the same configuration across multiple packages.
=> build: use shared rollup config

.changeset/ten-drinks-lay.md, packages/components-css/paragraph-css/src/_mixin.scss, packages/components-css/paragraph-css/src/html/_mixin.scss, packages/components-css/paragraph-css/src/html/_mixins.scss, packages/components-css/paragraph-css/src/html/paragraph.scss, packages/components-css/paragraph-css/src/paragraph.scss
Rename `_mixins.scss` -> `_mixin.scss`. We prefer singular over plural in these instances
=> refactor(paragraph-css): rename _mixins

npmpackagejsonlint.config.cjs, packages/docs/paragraph-docs/docs/anatomy.en.md, packages/docs/paragraph-docs/docs/anatomy.md, packages/docs/paragraph-docs/package.json, pnpm-workspace.yaml
- Add an override to npmpackagejsonlint.config.cjs to allow the CC0-1.0 license
=> feat: add paragraph-docs

package.json, packages/components-react/code-block-react/src/code-block.test.tsx, packages/components-react/code-react/src/code.test.tsx, packages/components-react/color-sample-react/src/color-sample.test.tsx, packages/components-react/heading-react/src/heading.test.tsx, packages/components-react/link-react/src/link.test.tsx, packages/components-react/mark-react/src/mark.test.tsx, packages/components-react/paragraph-react/src/paragraph.test.tsx, packages/components-react/skip-link-react/src/skip-link.test.tsx, pnpm-lock.yaml
Explicitly import `describe`, `expect`, and `it` from `@jest/globals` and run the side effect from `@testing-library/jest-dom/jest-globals`:
```js
import {expect} from '@jest/globals'
import * as extensions from './matchers'
expect.extend(extensions)
```
=> chore: remove @types/jest

packages/components-react/heading-1-react/package.json, packages/components-react/heading-1-react/src/heading-1.test.tsx, packages/components-react/heading-2-react/package.json, packages/components-react/heading-2-react/src/heading-2.test.tsx, packages/components-react/heading-2-react/src/heading-2.tsx, packages/components-react/heading-3-react/package.json, packages/components-react/heading-3-react/src/heading-3.test.tsx, packages/components-react/heading-4-react/package.json, packages/components-react/heading-4-react/src/heading-4.test.tsx, packages/components-react/heading-5-react/package.json, packages/components-react/heading-5-react/src/heading-5.test.tsx, packages/components-react/heading-6-react/package.json, packages/components-react/heading-6-react/src/heading-6.test.tsx
- Fix: Heading2 was rendering a h1
- Add all useful tests for heading-react -> heading-x-react
=> feat: add Heading-x tests

pnpm-lock.yaml
Add missing package entries in pnpm-lock.yaml
=> chore: add missing package entries

.changeset/thick-pumpkins-speak.md, .changeset/twelve-colts-melt.md, packages/components-css/paragraph-css/src/_mixin.scss, packages/components-css/paragraph-css/src/paragraph.scss, packages/components-react/paragraph-react/src/paragraph.test.tsx, packages/components-react/paragraph-react/src/paragraph.tsx
By the way — nu herinner ik me weer waarom de class name `__b` heette: in `scss` overschrijven de volgende mixin names elkaar:
1. `@mixin nl-paragraph--lead`
2. `@mixin nl-paragraph__lead`
=> fix: rename paragraph BEM class name element `__b` to `__lead`

packages/components-css/paragraph-css/src/_mixin.scss, packages/components-css/paragraph-css/src/paragraph.scss
Remove CSS custom properties from paragraph-css that were not based on tokens from paragraph-tokens
=> fix: align paragraph-css with paragraph-tokens

packages/docs/paragraph-docs/package.json
Reset the version of paragraph-docs back to 0.0.0 to see if changeset is going to suggest 1.0.0 as the new major version instead of 2.0.0 when it has not ever been published.
=> fix: paragraph-docs version

packages/components-react/data-badge-react/src/data-badge.tsx
Add a type guard for time and data props to remove the need to type cast restProps
=> chore: remove type casting in Data Badge

.github/workflows/continuous-deployment.yml, packages/components-react/code-block-react/jest.config.mjs, packages/components-react/code-react/jest.config.mjs, packages/components-react/color-sample-react/jest.config.mjs, packages/components-react/data-badge-react/jest.config.mjs, packages/components-react/heading-1-react/jest.config.mjs, packages/components-react/heading-2-react/jest.config.mjs, packages/components-react/heading-3-react/jest.config.mjs, packages/components-react/heading-4-react/jest.config.mjs, packages/components-react/heading-5-react/jest.config.mjs, packages/components-react/heading-6-react/jest.config.mjs, packages/components-react/heading-react/jest.config.mjs, packages/components-react/link-react/jest.config.mjs, packages/components-react/mark-react/jest.config.mjs, packages/components-react/number-badge-react/jest.config.mjs, packages/components-react/paragraph-react/jest.config.mjs, packages/components-react/skip-link-react/jest.config.mjs
Oops, didn't get the memo about #162
@matijs Even kijken of er ook in mijn approach wat snippets zitten die we willen gebruiken?
Ik kom wel heel erg op het punt dat ik een interne package wil hebben voor een shared config voor bijvoorbeeld `jest`.
=> ci: code coverage

packages/storybook-test/package.json, packages/storybook/package.json
The new command to run Storybook is:
`pnpm run storybook`
when run from inside `./packages/storybook` or
`./packages/storybook-test`
Or:
`pnpm --filter @nl-design-system-candidate/storybook run storybook`
When run from anywhere in the repository
=> chore: rename "start" -> "storybook"

packages/storybook-test/stories/link.stories.tsx
All links have `target="_blank"` and this needs pointing out in the link
=> feat: add more Link stories

stylelint.config.mjs
The HTML coverage files that Jest writes in a package's `coverage/` folder contains CSS that should be ignored by Stylelint.
=> chore: extend Stylelint ignore

packages/storybook-test/stories/paragraph.stories.tsx
- “rename” `children` to `text` in the API table
- rename the story exports to make a bit more sense
- explicitly set `lang="ar"` and `dir="rtl"` on the Arabic stories
- fix an issue where a `render()` method without arguments results in a broken code example.
=> refactor: Paragraph stories

packages/storybook-test/vite.config.mjs, packages/storybook/vite.config.mjs
By default Storybook's Vite configuration uses the legacy Dart Sass API that is deprecated now and will be removed in Dart Sass 2.0.0
Adding a Vite configuration makes sure that the modern Dart Sass API is used instead
=> chore: add Vite configs to Storybooks

.changeset/verander-maar.md, packages/docs/number-badge-docs/package.json, packages/docs/paragraph-docs/package.json
De number badge was nog niet publiek beschikbaar.
Voor paragraph en number badge was er in de `package.json` een `exports` property die niet bij andere docs gebruikt werd. 
De packages zonder `exports` heb ik geïmporteerd in de documentatiesite, bij die mèt expliciet `exports` kreeg ik een foutmelding over een niet-kloppend pad, bij de rest niet. 
Waarschijnlijk kan dit ook opgelost worden door een ander pad te gebruiken in de documentatiesite, maar in dat geval zou het netjes zijn om de andere packages een zelfde expliciete exports mee te geven? Ik heb geen voorkeur over wat mooier is.
=> Update exports (paragraph + number badge) & toegang (number badge)

packages/storybook-shared/src/StoryRootDecorator.tsx, packages/storybook-test/src/WcagAudit.ts, packages/storybook-test/src/WcagAuditReport.tsx, packages/storybook-test/src/wcag21.ts, packages/storybook-test/src/wcag22.ts, packages/storybook-test/stories/paragraph/paragraph.stories.tsx, packages/storybook/stories/paragraph.stories.tsx
Er zijn links nu losse URLs waar je stories kan testen, zoals bijvoorbeeld:
- https://candidate-storybook-test-git-docs-wcag-links-nl-design-system.vercel.app/iframe.html?id=componenten-paragraph--paragraph-lead-arabic&args=&globals=&viewMode=story
Deze pagina's hebben nu `<html lang=".." dir="..."><head><title>...</title>` zodat ook Language of the Page and Page Titled succesvol getest kunnen worden.
Elke story kan nu een eigen toegankelijkheidsverklaring hebben, door een `wcagAudit` onder de `parameters` van een Story. Die wordt samengevoegd met de `wcagAudit` van de `meta`, zodat je niet alles bij elke test hoeft te herhalen.
De audit bij een Story kan een eigen tester hebben, met een eigen testdatum.
Algemeen gedeelte:
Per Story:
=> docs: log a11y test findings with links to NL Design System

packages/storybook-non-conforming/package.json, packages/storybook-test/package.json, packages/storybook-test/stories/color-sample/color-sample.stories.tsx, packages/storybook/package.json, pnpm-lock.yaml
=> docs: improve story descriptions for Color Sample

.github/workflows/continuous-deployment.yml
Correct the version number in the comment as well, this was suggesting v4.0.1 but was in fact v5.0.7
Replaces #420
=> chore: update codecov/codecov-action

packages/storybook-test/stories/link/link.stories.tsx
Best practice is om de toegankelijke naam van een link te beginnen met de visuele tekst. De dot in de tekst is overbodig, gebruik voor een korte pauze beter een komma.
De `aria-current` ontbrak op de link voor het verhaal “Link rondom image, current page” en is nu toegevoegd.
De toegankelijke naam staat op de SVG.
Vergelijkbaar met het geval van een img met een alt attribuut.
ZIe voor uitleg: https://www.htmhell.dev/adventcalendar/2024/1/
Preview: https://candidate-storybook-test-git-fix-logo-i-ae48c3-nl-design-system.vercel.app/?path=/docs/componenten-link--documentatie
Gerelateerd issue: https://github.com/nl-design-system/candidate/issues/210
=> fix: Verplaats het aria-label op de link naar de SVG en voeg de ontbrekende aria-current toe

package.json
Dependabot uses the package.json#engines.node field to determine the Node.js version to use. It currently does not work with Node.js 22 so allow Node.js 20 as well.
=> chore: broaden package.json#engines.node range

.github/workflows/block-autosquash-commits.yml
The workflow did not have a sensible name, probably got mixed up with the event :)
=> fix: workflow name

.github/workflows/changeset-status.yml, .github/workflows/publish.yml
Provenance needs `id-token: write`
Skip the changeset-status workflow for the nl-design-system-ci actor
=> fix: provenance

.github/workflows/changeset-status.yml
Only run changeset-status if the branch being merged does not start with `changeset-release/`
=> fix: conditionally run changeset-status

.changeset/beige-owls-play.md, packages/components-css/code-block-css/package.json, packages/components-css/code-css/package.json, packages/components-css/color-sample-css/package.json, packages/components-css/data-badge-css/package.json, packages/components-css/heading-1-css/package.json, packages/components-css/heading-2-css/package.json, packages/components-css/heading-3-css/package.json, packages/components-css/heading-4-css/package.json, packages/components-css/heading-5-css/package.json, packages/components-css/heading-6-css/package.json, packages/components-css/heading-css/package.json, packages/components-css/link-css/package.json, packages/components-css/mark-css/package.json, packages/components-css/number-badge-css/package.json, packages/components-css/paragraph-css/package.json, packages/components-css/skip-link-css/package.json
Met de gefixte workflow zou er na het mergen van deze PR een PR geopend moeten worden die niet ten onrechte geflagged wordt door de changeset-status workflow.
=> chore: provenance components-css

.changeset/lazy-worms-travel.md, packages/tokens/paragraph-tokens/tokens.json
The following tokens were added:
- `nl.paragraph.margin-block-start`
- `nl.paragraph.margin-block-end`
- `nl.paragraph.lead.margin-block-start`
- `nl.paragraph.lead.margin-block-end`
=> feat(paragraph-tokens): add new tokens

.changeset/tender-readers-search.md, packages/tokens/link-tokens/tokens.json
The following tokens were removed:
- `nl.link.active.text-decoration-line`
- `nl.link.active.text-decoration-thickness`
- `nl.link.focus-visible.background-color`
- `nl.link.focus-visible.color`
- `nl.link.focus-visible.text-decoration-line`
- `nl.link.focus-visible.text-decoration-thickness`
=> refactor(link-tokens): remove tokens

.changeset/brave-pillows-allow.md, packages/components-css/link-css/src/_mixin.scss
Bring token usage in `@nl-design-system-candidate/link-css` in line with what is available in `@nl-design-system-candidate/link-tokens`.
Remove all references to focus as that will be taken care of by a common focus state.
Replace placeholder tokens with disabled tokens.
Remove font-weight from `nl-link--disabled` and `nl-link--current`.
=> refactor(link-css): update tokens

.github/workflows/changeset-status.yml
Make sure that the changeset status workflow can run succesfully for Dependabot pull requests as well.
=> ci: improve the 'changeset status' workflow

.github/CODEOWNERS, .github/dependabot.yml
Remove `reviewers` from the Dependabot configuration. See [this GitHub blogpost][1].
Add `.github/CODEOWNERS`.
[1]: https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
=> chore: update Dependabot config

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/docs.yml, CONTRIBUTING.md
- Voegt CONTRIBUTING.md toe.
- Refereert naar CONTRIBUTING.md in issue templates, om duidelijk te maken dat men eerst de repository moet forken om code te kunnen bijdragen.
Closes #548
=> docs: CONTRIBUTING toevoegen (#548)

.github/dependabot.yml, .ncurc.major.cjs, .ncurc.minor.cjs, .ncurc.patch.cjs
Prevent Dependabot from updating Storybook to Storybook 9 as well as the 2 third party addons we use.
We cannot update yet because `@whitespace/storybook-addon-html` is not yet compatible with Storybook 9.
=> ci: update Dependabot ignores

.changeset/wise-cougars-stay.md, packages/components-react/data-badge-react/package.json, packages/components-react/data-badge-react/src/data-badge.tsx, pnpm-lock.yaml
Add missing devDependencies so @nl-design-system-candidate/data-badge-react can be built on its own.
Replace clsx with a oneliner equivalent.
Simplify DataBadgeProps by getting rid of the intermediary DataBadgePropsForTime and DataBadgePropsForData.
Fix the original props for <data> where the value attribute came from `DataHTMLAttributes<HTMLTimeElement>['value']` instead of `DataHTMLAttributes<HTMLDataElement>['value']`.
=> refactor: data-badge-react

.changeset/curvy-steaks-refuse.md, .changeset/sharp-loops-roll.md, packages/components-react/heading-react/package.json, packages/components-react/heading-react/src/heading.ts, pnpm-lock.yaml
Remove the clsx dependency and replace it with a oneliner equivalent to concatenate classNames.
Add missing devDependencies so @nl-design-system-candidate/heading-react can be built on its own.
=> refactor: heading-react

.github/workflows/codecov.yml, .github/workflows/continuous-integration.yml
Move the codecov action to its own file and make sure it runs when the "Continuous Integration" workflow was succesful.
This should make it possible for the codecov action to run for pull requests from forks and have secrets be available without leaking secrets to the pull request.
=> ci: move codecov to its own file

packages/storybook-test/stories/heading/heading.stories.tsx
=> fix: Heading level 6 story

.github/workflows/changeset-status.yml
Always run the changeset-status workflow regardless of the github.actor or the name of the branch.
Add comments to clarify what's happening in every step.
=> refactor: changeset-status workflow

.github/workflows/codecov.yml, .github/workflows/continuous-integration.yml
In the Continuous Integration workflow, run test:coverage and upload a coverage-report artifact.
In the Codecov for pull requests workflow, download the coverage-report artifact and upload it using codecov/codecov-action
=> refactor: codevov workflow

packages/storybook-non-conforming/package.json, packages/storybook-non-conforming/stories/code-block.stories.tsx, packages/storybook-non-conforming/stories/code.stories.tsx, packages/storybook-non-conforming/stories/mark.stories.tsx, packages/storybook-non-conforming/stories/paragraph.stories.tsx, packages/storybook-test/config/main.ts, packages/storybook-test/stories/code-block.stories.tsx, packages/storybook-test/stories/code.stories.tsx, packages/storybook-test/stories/color-sample.stories.tsx, packages/storybook-test/stories/data-badge.stories.tsx, packages/storybook-test/stories/heading.stories.tsx, packages/storybook-test/stories/icon.stories.tsx, packages/storybook-test/stories/link.stories.tsx, packages/storybook-test/stories/mark.stories.tsx, packages/storybook-test/stories/number-badge.stories.tsx, packages/storybook-test/stories/paragraph.stories.tsx, packages/storybook-test/stories/skip-link.stories.tsx, packages/storybook/package.json, packages/storybook/stories/code-block.stories.tsx, packages/storybook/stories/code.stories.tsx, packages/storybook/stories/color-sample.stories.tsx, packages/storybook/stories/data-badge.stories.tsx, packages/storybook/stories/heading.stories.tsx, packages/storybook/stories/icon.stories.tsx, packages/storybook/stories/link.stories.tsx, packages/storybook/stories/mark.stories.tsx, packages/storybook/stories/number-badge.stories.tsx, packages/storybook/stories/paragraph.stories.tsx, packages/storybook/stories/skip-link.stories.tsx, pnpm-lock.yaml
Import the React component and CSS component code separately in the Storybooks in:
- @nl-design-system-candidate/storybook,
- @nl-design-system-candidate/storybook-test
- @nl-design-system-candidate/storybook-non-conforming
We do this instead of importing the convenience `/css` export that the React components provide. This makes it easier to have a running storybook that automatically updates whilst changes to the React and CSS code can be made with stories automatically updating.
Helper components, usually @nl-design-system-candidate/paragraph-react or @nl-design-system-candidate/heading-react are imported as before, from their `/css` convenience exports. Where needed these were added as an extra devDependency to the storybook's package.json.
Remove the unnecessary component-name …
=> chore: storybook component imports

.github/workflows/chromatic.yml, .github/workflows/codecov.yml
Clarify why actions/download-artifact needs github.token
=> chore: document actions/download-artifact
