.changeset/serious-shrimps-listen.md, .markdownlintignore, packages/components-react/paragraph-react/LICENSE.md, packages/components-react/paragraph-react/README.md
- Add LICSENSE.md
- Add README.md
- Add changset
=> docs: paragraph-react

.changeset/itchy-emus-deny.md, packages/components-css/paragraph-css/LICENSE.md, packages/components-css/paragraph-css/README.md
- LICENSE.md
- README.md
- changeset
=> docs: paragraph css

.ncurc.major.cjs, package.json
Change `"//comment"` to `"//"`. See [this thread][1] for the reasoning why.
[1]: https://groups.google.com/g/nodejs/c/NmL7jdeuw0M/m/yTqI05DRQrIJ
=> chore: add @types/node to .ncurc.major.cjs

.changeset/silver-rice-marry.md, packages/components-css/paragraph-css/src/_mixins.scss
refactor: remove `--nl-document-*` tokens
=> refactor:paragraph

package.json
=> chore: update package.json#packageManager

packages/components-react/heading-react/LICENSE.md, packages/components-react/heading-react/README.md, packages/components-react/heading-react/babel.config.cjs, packages/components-react/heading-react/jest.config.mjs, packages/components-react/heading-react/package.json, packages/components-react/heading-react/rollup.config.mjs, packages/components-react/heading-react/src/css.ts, packages/components-react/heading-react/src/heading.test.tsx, packages/components-react/heading-react/src/heading.ts, packages/components-react/heading-react/tsconfig.build.json, packages/components-react/heading-react/tsconfig.json, pnpm-lock.yaml
Add stub for the Heading candidate component
=> feat: add <Heading>

packages/components-css/skip-link-css/LICENSE.md, packages/components-css/skip-link-css/README.md, packages/components-css/skip-link-css/package.json, packages/components-css/skip-link-css/src/_mixin.scss, packages/components-css/skip-link-css/src/skip-link.scss, packages/components-react/skip-link-react/LICENSE.md, packages/components-react/skip-link-react/README.md, packages/components-react/skip-link-react/babel.config.cjs, packages/components-react/skip-link-react/jest.config.mjs, packages/components-react/skip-link-react/package.json, packages/components-react/skip-link-react/rollup.config.mjs, packages/components-react/skip-link-react/src/css.tsx, packages/components-react/skip-link-react/src/skip-link.test.tsx, packages/components-react/skip-link-react/src/skip-link.tsx, packages/components-react/skip-link-react/tsconfig.build.json, packages/components-react/skip-link-react/tsconfig.json, pnpm-lock.yaml
- Add @nl-design-system-candidate/skip-link-react
- Add @nl-design-system-candidate/skip-link-css
=> feat: add <SkipLink> React component and CSS

packages/tokens/code-block-tokens/LICENSE.md, packages/tokens/code-block-tokens/README.md, packages/tokens/code-block-tokens/package.json, packages/tokens/code-block-tokens/tokens.json
- Add @nl-design-system-candidate/code-block-tokens
=> feat: add design token defintions for Code Block

packages/tokens/skip-link-tokens/LICENSE.md, packages/tokens/skip-link-tokens/README.md, packages/tokens/skip-link-tokens/package.json, packages/tokens/skip-link-tokens/tokens.json
- Add @nl-design-system-candidate/skip-link-tokens
=> feat: add design token definitions for Skip Link

package.json, packages/components-react/heading-react/package.json, packages/components-react/heading-react/src/heading.test.tsx, packages/components-react/heading-react/src/heading.ts, pnpm-lock.yaml
- Add `"test:watch"` script to conveniently retest while writing tests
- Add tests
=> feat: add Heading tests

packages/components-css/code-block-css/LICENSE.md, packages/components-css/code-block-css/README.md, packages/components-css/code-block-css/package.json, packages/components-css/code-block-css/src/_mixin.scss, packages/components-css/code-block-css/src/code-block.scss, packages/components-css/code-block-css/src/html/_mixin.scss, packages/components-css/code-block-css/src/html/code-block.scss, packages/components-react/code-block-react/LICENSE.md, packages/components-react/code-block-react/README.md, packages/components-react/code-block-react/babel.config.cjs, packages/components-react/code-block-react/jest.config.mjs, packages/components-react/code-block-react/package.json, packages/components-react/code-block-react/rollup.config.mjs, packages/components-react/code-block-react/src/code-block.test.tsx, packages/components-react/code-block-react/src/code-block.tsx, packages/components-react/code-block-react/src/css.tsx, packages/components-react/code-block-react/tsconfig.build.json, packages/components-react/code-block-react/tsconfig.json, pnpm-lock.yaml
- Add @nl-design-system-candidate/code-block-react
- Add @nl-design-system-candidate/code-block-css
=> feat: add <CodeBlock> React component and CSS

packages/components-css/color-sample-css/LICENSE.md, packages/components-css/color-sample-css/README.md, packages/components-css/color-sample-css/package.json, packages/components-css/color-sample-css/src/_mixin.scss, packages/components-css/color-sample-css/src/color-sample.scss, packages/components-react/color-sample-react/LICENSE.md, packages/components-react/color-sample-react/README.md, packages/components-react/color-sample-react/babel.config.cjs, packages/components-react/color-sample-react/jest.config.mjs, packages/components-react/color-sample-react/package.json, packages/components-react/color-sample-react/rollup.config.mjs, packages/components-react/color-sample-react/src/color-sample.test.tsx, packages/components-react/color-sample-react/src/color-sample.tsx, packages/components-react/color-sample-react/src/css.tsx, packages/components-react/color-sample-react/tsconfig.build.json, packages/components-react/color-sample-react/tsconfig.json, pnpm-lock.yaml
- Add @nl-design-system-candidate/color-sample-react
- Add @nl-design-system-candidate/color-sample-css
=> feat: add <ColorSample> React component and CSS

.changeset/clever-seals-cover.md, package.json, packages/components-react/paragraph-react/package.json, packages/components-react/paragraph-react/src/paragraph.test.tsx, packages/components-react/paragraph-react/src/paragraph.tsx, packages/storybook/src/paragraph.stories.tsx, pnpm-lock.yaml
Replace the `appearance` prop with a `purpose` prop.
Add tests.
=> refactor: Paragraph props

packages/components-css/data-badge-css/LICENSE.md, packages/components-css/data-badge-css/README.md, packages/components-css/data-badge-css/package.json, packages/components-css/data-badge-css/src/_mixin.scss, packages/components-css/data-badge-css/src/data-badge.scss, packages/components-react/data-badge-react/LICENSE.md, packages/components-react/data-badge-react/README.md, packages/components-react/data-badge-react/babel.config.cjs, packages/components-react/data-badge-react/jest.config.mjs, packages/components-react/data-badge-react/package.json, packages/components-react/data-badge-react/rollup.config.mjs, packages/components-react/data-badge-react/src/css.tsx, packages/components-react/data-badge-react/src/data-badge.test.tsx, packages/components-react/data-badge-react/src/data-badge.tsx, packages/components-react/data-badge-react/tsconfig.build.json, packages/components-react/data-badge-react/tsconfig.json, pnpm-lock.yaml
- @nl-design-system-candidate/data-badge-react
- @nl-design-system-candidate/data-badge-css
=> feat: add <DataBadge> React component and CSS

packages/tokens/data-badge-tokens/LICENSE.md, packages/tokens/data-badge-tokens/README.md, packages/tokens/data-badge-tokens/package.json, packages/tokens/data-badge-tokens/tokens.json
Use "dimension" instead of "sizing" and "spacing"
=> feat: add design token definition for Data Badge

packages/tokens/code-block-tokens/tokens.json
Use "dimension" instead of "spacing"
=> feat: update design token definition for Code Block

lint-staged.config.mjs
Try to fix linting issues just before committing. Failing to fix will still result in the commit not going through.
=> build: update lint-staged config

packages/components-css/mark-css/src/_mixin.scss, packages/storybook/stories/mark.stories.tsx
Add basic styling for Mark based on the Mark tokens
=> feat: add Mark stories

.github/workflows/a11y-alt-text-bot.yml
Run checks for alt-texts for issues, pull requests, issue comments, discussions, and discussion comments
=> build: run alt-text checks

packages/storybook/stories/heading.stories.tsx, pnpm-lock.yaml
Add Heading to Storybook.
Add @storybook/addon-controls to allow changing props for a story
=> feat: add Heading stories

packages/docs/code-block-docs/docs/anatomy.md, packages/docs/code-docs/docs/anatomy.md, packages/docs/color-sample-docs/docs/anatomy.md, packages/docs/data-badge-docs/docs/anatomy.md, packages/docs/heading-docs/docs/anatomy.md, packages/docs/link-docs/docs/anatomy.md, packages/docs/mark-docs/docs/anatomy.md, packages/docs/paragraph-docs/docs/anatomy.md, packages/docs/skip-link-docs/docs/anatomy.md
- code-block
- code
- color-sample
- data-badge
- heading
- link
- mark
- paragraph
- skip-link
=> docs: add anatomy

packages/docs/code-block-docs/docs/anatomy.en.md, packages/docs/code-docs/docs/anatomy.en.md, packages/docs/color-sample-docs/docs/anatomy.en.md, packages/docs/data-badge-docs/docs/anatomy.en.md, packages/docs/heading-1-docs/docs/anatomy.en.md, packages/docs/heading-2-docs/docs/anatomy.en.md, packages/docs/heading-3-docs/docs/anatomy.en.md, packages/docs/heading-4-docs/docs/anatomy.en.md, packages/docs/heading-5-docs/docs/anatomy.en.md, packages/docs/heading-6-docs/docs/anatomy.en.md, packages/docs/heading-docs/docs/anatomy.en.md, packages/docs/link-docs/docs/anatomy.en.md, packages/docs/mark-docs/docs/anatomy.en.md, packages/docs/number-badge-docs/docs/anatomy.en.md, packages/docs/paragraph-docs/docs/anatomy.en.md, packages/docs/skip-link-docs/docs/anatomy.en.md
We'll re-add them if and when needed
=> chore: remove empty files

.github/ISSUE_TEMPLATE/1-meer-dan-twee-themas.md
Ik heb een eerste template aangemaakt en wil zien of dit werkt.
=> Create (1) >2 thema's

.github/ISSUE_TEMPLATE/1-meer-dan-twee-themas.md
Changes:
- Name change of the template
- About change of the template (description)
- 'Candidate' label removed
=> build: issue-template > name change, about change

packages/tokens/heading-tokens/LICENSE.md, packages/tokens/heading-tokens/README.md, packages/tokens/heading-tokens/package.json, packages/tokens/heading-tokens/tokens.json
Add the tokens package for the Heading component
=> feat: add @nl-design-system-candidate/heading-tokens

.github/ISSUE_TEMPLATE/2-documentatie-aliassen.md
Created a new template about alias documentation
=> build: Create 2-documentatie-aliassen.md

packages/storybook-test/src/Arabic.tsx, packages/storybook-test/src/English.tsx, packages/storybook-test/src/German.tsx, packages/storybook-test/stories/heading.stories.tsx
Add German, English, and Arabic decorators
Add a German example and replace the I18nDecorator with the Arabic decorator
=> feat: simplify language decorators

.github/ISSUE_TEMPLATE/a11y-getest.md
Template aangepast om beter aan te sluiten op de werkwijze van Marjon en Rian.
Dit template kan worden gebruikt voor componenten in Community en Candidate.
Preview: https://github.com/nl-design-system/candidate/blob/4e8ad3d11f2d16f107ce6f71533e9180c7e3becd/.github/ISSUE_TEMPLATE/a11y-getest.md
=> docs: change setup a11y review templates

packages/components-css/heading-1-css/package.json, packages/components-css/heading-2-css/package.json, packages/components-css/heading-3-css/package.json, packages/components-css/heading-4-css/package.json, packages/components-css/heading-6-css/package.json, packages/components-css/heading-css/LICENSE.md, packages/components-css/heading-css/README.md, packages/components-css/heading-css/package.json, packages/components-css/heading-css/src/_mixin.scss, packages/components-css/heading-css/src/heading.scss, packages/components-css/heading-css/src/html/_mixin.scss, packages/components-css/heading-css/src/html/heading.scss, packages/components-react/heading-react/package.json, packages/components-react/heading-react/src/css.ts, pnpm-lock.yaml
- Fix the package.json#description field for the heading-n-css packages
- Add @nl-design-system-candidate/heading-css
- Use the new @nl-design-system-candidate/heading-css package instead of
the individual @nl-design-system-candidate/heading-n-css packages
- Get the package ready for publication
=> chore: Heading styles

packages/storybook-test/config/preview.ts, packages/storybook-test/config/statuses.ts, packages/storybook-test/stories/paragraph.stories.tsx
Welke statussen hebben we per direct nodig?
=> chore: add Storybook Tests statuses

packages/storybook-test/stories/paragraph.stories.tsx
- Zoom 400%
- Small viewport
- Zoom 400% + small viewport
=> feat: Paragraph extra stories

packages/components-css/number-badge-css/src/_mixin.scss, packages/components-css/number-badge-css/src/number-badge.scss, packages/components-css/number-badge-css/src/test.scss, packages/storybook-test/stories/number-badge/number-badge.stories.tsx
=> feat: add Number Badge

packages/storybook-test/package.json, packages/storybook-test/src/DesignTokens.tsx, packages/storybook-test/src/DocsPage.tsx, packages/storybook-test/stories/code-block/code-block.stories.tsx, packages/storybook-test/stories/code/code.stories.tsx, packages/storybook-test/stories/color-sample/color-sample.stories.tsx, packages/storybook-test/stories/data-badge/data-badge.stories.tsx, packages/storybook-test/stories/heading/heading.stories.tsx, packages/storybook-test/stories/link/link.stories.tsx, packages/storybook-test/stories/mark/mark.stories.tsx, packages/storybook-test/stories/number-badge/number-badge.stories.tsx, packages/storybook-test/stories/paragraph/paragraph.stories.tsx, pnpm-lock.yaml
Toon een tabel met design tokens onderaan de documentatie voor een component
=> feat: Design Tokens Table

README.md, package.json, packages/storybook-test/package.json
Gemaakt op Estafettemodeldag, even verplaatst naar losse PR
=> docs: onboarding for contributing test stories

packages/components-css/code-block-css/src/_mixin.scss, packages/components-css/code-block-css/src/code-block.scss, packages/components-css/code-block-css/src/html/_mixin.scss, packages/components-react/code-block-react/src/code-block.test.tsx, packages/components-react/code-block-react/src/code-block.tsx, packages/storybook-test/config/preview.ts, packages/storybook-test/package.json, packages/storybook-test/stories/code-block/code-block.stories.tsx, packages/storybook-test/stories/code-block/nonconforming.stories.tsx, pnpm-lock.yaml
=> feat: Code Block CSS

.changeset/happy-hounds-hope.md, .changeset/itchy-carpets-visit.md, .changeset/slimy-tomatoes-look.md, .changeset/tame-hats-fly.md, .changeset/wicked-impalas-exist.md, packages/components-css/code-block-css/package.json, packages/components-css/code-css/CHANGELOG.md, packages/components-css/heading-css/CHANGELOG.md, packages/components-css/mark-css/package.json, packages/components-react/code-block-react/package.json, packages/components-react/code-react/package.json, packages/components-react/heading-react/package.json, packages/components-react/mark-react/package.json, packages/tokens/code-block-tokens/package.json, packages/tokens/code-tokens/package.json, packages/tokens/heading-tokens/package.json, packages/tokens/mark-tokens/package.json, packages/tokens/paragraph-tokens/package.json
Depends on #364 and #358 — merge those first.
=> chore: release components

packages/storybook-test/package.json, packages/storybook/package.json, pnpm-lock.yaml
This update brings a sufficient contrast for Mark.
=> build: update voorbeeld-theme design tokens

packages/components-css/color-sample-css/src/_mixin.scss, packages/components-react/color-sample-react/src/color-sample.test.tsx, packages/components-react/color-sample-react/src/color-sample.tsx, packages/storybook-test/stories/color-sample/color-sample.stories.tsx, packages/tokens/color-sample-tokens/tokens.json
- Use an SVG instead of a <data> element
- Update unit tests
- Update CSS
- Update stories
=> refactor: Color Sample component

packages/components-react/mark-react/README.md
=> docs: Mark README

package.json, packages/storybook-non-conforming/@types/markdown.d.ts, packages/storybook-non-conforming/LICENSE.md, packages/storybook-non-conforming/README.md, packages/storybook-non-conforming/config/main.ts, packages/storybook-non-conforming/config/preview.ts, packages/storybook-non-conforming/config/statuses.ts, packages/storybook-non-conforming/config/viewports.ts, packages/storybook-non-conforming/package.json, packages/storybook-non-conforming/src/DocsPage.tsx, packages/storybook-non-conforming/src/TextDecorator.tsx, packages/storybook-non-conforming/stories/code-block/code-block.stories.tsx, packages/storybook-non-conforming/stories/code/code.stories.tsx, packages/storybook-non-conforming/stories/color-sample/color-sample.stories.tsx, packages/storybook-non-conforming/stories/data-badge/data-badge.stories.tsx, packages/storybook-non-conforming/stories/heading/heading.stories.tsx, packages/storybook-non-conforming/stories/link/link.stories.tsx, packages/storybook-non-conforming/stories/mark/mark.stories.tsx, packages/storybook-non-conforming/stories/number-badge/number-badge.stories.tsx, packages/storybook-non-conforming/stories/paragraph/paragraph.stories.tsx, packages/storybook-non-conforming/tsconfig.json, packages/storybook-non-conforming/vite.config.mjs, pnpm-lock.yaml
- Move non-conforming stories from Storybook Test -> Storybook Non-conforming
=> feat: add Storybook Non-conforming

packages/components-react/color-sample-react/README.md, packages/components-react/color-sample-react/src/color-sample.test.tsx, packages/components-react/color-sample-react/src/color-sample.tsx
- update Color Sample README
- change `title` -> `label` prop for Color Sample
=> docs: Color Sample

packages/storybook-shared/src/StoryRootDecorator.tsx, packages/storybook-shared/tsconfig.json
Use the Storybook API and make sure TS knows about DOM
=> fix: Storybook viewMode

.changeset/slimy-kings-cry.md, .changeset/sweet-papayas-approve.md, .changeset/tasty-dryers-behave.md, packages/components-css/number-badge-css/src/_mixin.scss, packages/components-css/number-badge-css/src/number-badge.scss, packages/components-react/number-badge-react/src/number-badge.test.tsx, packages/components-react/number-badge-react/src/number-badge.tsx, packages/storybook-test/stories/number-badge/number-badge.stories.tsx, packages/storybook/stories/number-badge.stories.tsx
=> feat: add Number Badge label

.changeset/four-phones-trade.md, packages/components-react/paragraph-react/package.json
npm en GitHub Actions regelen dit allemaal automagisch...
=> chore: add provenance to paragraph-react

.changeset/gorgeous-apricots-lie.md, packages/docs/code-block-docs/package.json, packages/docs/code-docs/package.json, packages/docs/color-sample-docs/package.json, packages/docs/data-badge-docs/package.json, packages/docs/heading-docs/package.json, packages/docs/link-docs/package.json, packages/docs/mark-docs/package.json, packages/docs/number-badge-docs/package.json, packages/docs/paragraph-docs/package.json, packages/docs/skip-link-docs/package.json
=> chore: add provenance to docs packages

.changeset/README.md, package.json
Toevoegen en valideren van missende documentatie in https://github.com/nl-design-system/documentatie/pull/1036 en vervolgens hiernaar refereren in de README.
Part of but does not close #1246.
=> feat: corrigeer en verbeter community developer ervaring met changesets (#1246)

.changeset/long-eggs-wait.md, packages/components-css/paragraph-css/src/_mixin.scss
The following tokens were added:
- `--nl-paragraph-margin-block-start`
- `--nl-paragraph-margin-block-end`
- `--nl-paragraph-lead-margin-block-start`
- `--nl-paragraph-lead-margin-block-end`
=> feat(paragraph-css): add new tokens

.changeset/loud-games-breathe.md, packages/tokens/heading-tokens/tokens.json
Add:
- `nl.heading.level-1.margin-block-start`
- `nl.heading.level-1.margin-block-end`
- `nl.heading.level-2.margin-block-start`
- `nl.heading.level-2.margin-block-end`
- `nl.heading.level-3.margin-block-start`
- `nl.heading.level-3.margin-block-end`
- `nl.heading.level-4.margin-block-start`
- `nl.heading.level-4.margin-block-end`
- `nl.heading.level-5.margin-block-start`
- `nl.heading.level-5.margin-block-end`
- `nl.heading.level-6.margin-block-start`
- `nl.heading.level-6.margin-block-end`
=> feat(heading-tokens): Add new tokens

.changeset/three-worms-run.md, packages/components-css/heading-css/src/_mixin.scss
Add:
- `nl-heading-level-1-margin-block-start`
- `nl-heading-level-1-margin-block-end`
- `nl-heading-level-2-margin-block-start`
- `nl-heading-level-2-margin-block-end`
- `nl-heading-level-3-margin-block-start`
- `nl-heading-level-3-margin-block-end`
- `nl-heading-level-4-margin-block-start`
- `nl-heading-level-4-margin-block-end`
- `nl-heading-level-5-margin-block-start`
- `nl-heading-level-5-margin-block-end`
- `nl-heading-level-6-margin-block-start`
- `nl-heading-level-6-margin-block-end`
=> feat(heading-css): Add new tokens

.github/workflows/changeset-status.yml
Document why `fetch-depth: 0` is needed.
=> docs: improve changeset-status workflow

README.md
There are no changes between this commit and the previous one. This commit is to trigger a baseline for Chromatic
=> ci: chromatic baseline

.github/workflows/visual-regression-test.yml
- fix typo because `event_name` was misspelled
- move `if:` clause because the entire workflow should be run conditionally, not just the Chromatic action
=> fix: chromatic ci

.github/workflows/changeset-status.yml
Trigger changeset-status from the Continuous Integration workflow because it too needs secrets.
=> ci: update changeset-status

.npmrc, .prettierignore, package.json, pnpm-workspace.yaml, prettier.config.mjs
- Use .npmrc, .prettierignore, prettier.config.mjs from the example repo
- Bump package.json#packageManager
=> chore: repo hygiene

.github/workflows/chromatic.yml
=> fix: remove dryrun
